#  ┳┳┓┏┓┏┳┓┳┳┏┓┏┓┳┓  ┓┏┓┳┏┳┓┏┳┓┓┏
#  ┃┃┃┣┫ ┃ ┃┃┃┓┣ ┃┃━━┃┫ ┃ ┃  ┃ ┗┫
#  ┛ ┗┛┗ ┻ ┗┛┗┛┗┛┛┗  ┛┗┛┻ ┻  ┻ ┗┛
#                                


# Core Colors
background            #121212 
foreground            #e6e6e6
selection_foreground  {{ colors.primary.default.hex }}
selection_background  {{ colors.on_primary.default.hex }}
cursor                {{ colors.primary.default.hex }}
cursor_text_color     {{ colors.surface.default.hex }}

# Regular Colors
color0  {{ colors.surface.default.hex }}               
color1  #ff5c5c                
color2  #4cd964            
color3  {{ colors.tertiary.default.hex }}              
color4  {{ colors.on_primary_container.default.hex }}  
color5  {{ colors.on_secondary_container.default.hex }}
color6  {{ colors.secondary.default.hex }}             
color7  #b8b8b8

# Bright Colors
color8  #3a3a3a        
color9  {{ colors.error.default.hex }}                  
color10 {{ colors.primary.default.hex }}                
color11 {{ colors.tertiary.default.hex }}               
color12 {{ colors.on_primary_container.default.hex }}   
color13 {{ colors.on_secondary_container.default.hex }} 
color14 {{ colors.secondary.default.hex }}              
color15 #ffffff
